from __future__ import annotations

import html
import warnings
from pathlib import Path

warnings.filterwarnings("ignore", message="Pandas requires version .*", category=UserWarning)

import pandas as pd

from . import __version__
from .metrics import (
    choose_time_column,
    experiment_summary,
    fairness_over_time,
    flow_aggregates,
    interval_summary,
    resample_time_bins,
    total_from_bins,
    total_aggregate,
)
from .plots import PlotArtifact


def write_report(
    intervals: pd.DataFrame,
    summaries: pd.DataFrame,
    runs: pd.DataFrame,
    artifacts: list[PlotArtifact],
    out_path: Path,
    *,
    time_mode: str = "relative",
) -> Path:
    """Write a self-contained experiment summary that references generated plots."""

    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    flow_df = flow_aggregates(intervals)
    time_col = choose_time_column(flow_df, time_mode) if not flow_df.empty else choose_time_column(intervals, time_mode)
    flow_bins = resample_time_bins(flow_df, entity_col="flow_id", time_mode=time_mode) if not flow_df.empty else pd.DataFrame()
    stream_bins = resample_time_bins(intervals, entity_col="stream_id", time_mode=time_mode)
    total_df = total_from_bins(flow_bins) if not flow_bins.empty else total_aggregate(flow_df, time_col) if not flow_df.empty else pd.DataFrame()
    stream_summary = interval_summary(intervals, "stream_id")
    flow_summary = interval_summary(flow_df, "flow_id") if not flow_df.empty else pd.DataFrame()
    experiment_df = experiment_summary(flow_summary)
    flow_fairness = fairness_over_time(flow_bins, "flow_id", "time_bin_start_s") if not flow_bins.empty else pd.DataFrame()
    stream_fairness = fairness_over_time(stream_bins, "stream_id", "time_bin_start_s") if not stream_bins.empty else pd.DataFrame()

    cards = _metric_cards(
        intervals=intervals,
        runs=runs,
        total_df=total_df,
        flow_fairness=flow_fairness,
        stream_fairness=stream_fairness,
    )

    image_sections = "\n".join(_plot_section(artifact, out_path.parent) for artifact in artifacts if artifact.path.suffix == ".png")
    html_body = f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>iperf3 Plotter Report</title>
  <style>
    body {{ margin: 0; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; color: #202124; background: #f7f8fa; }}
    header {{ padding: 28px 40px; background: #13233a; color: white; }}
    main {{ max-width: 1180px; margin: 0 auto; padding: 28px; }}
    h1 {{ margin: 0 0 6px; font-size: 28px; }}
    h2 {{ margin-top: 32px; font-size: 20px; }}
    .muted {{ color: #5f6b7a; }}
    .cards {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(170px, 1fr)); gap: 12px; }}
    .card {{ background: white; border: 1px solid #d9dee7; border-radius: 8px; padding: 14px; }}
    .card strong {{ display: block; font-size: 22px; margin-top: 6px; }}
    figure {{ margin: 18px 0; background: white; border: 1px solid #d9dee7; border-radius: 8px; padding: 16px; }}
    figure img {{ width: 100%; height: auto; display: block; }}
    figcaption {{ margin-top: 10px; color: #4d5968; }}
    table {{ border-collapse: collapse; width: 100%; background: white; border: 1px solid #d9dee7; }}
    th, td {{ padding: 8px 10px; border-bottom: 1px solid #eef1f5; text-align: right; }}
    th:first-child, td:first-child {{ text-align: left; }}
    th {{ background: #eef2f7; font-weight: 650; }}
    .table-wrap {{ overflow-x: auto; }}
  </style>
</head>
<body>
  <header>
    <h1>iperf3 Plotter Report</h1>
    <div>Generated by iperf3_plotter {html.escape(__version__)}</div>
  </header>
  <main>
    <section class="cards">
      {cards}
    </section>
    <h2>Plots</h2>
    {image_sections}
    <h2>Runs</h2>
    <div class="table-wrap">{_table(runs)}</div>
    <h2>Flow Summary</h2>
    <div class="table-wrap">{_table(flow_summary)}</div>
    <h2>Experiment Summary</h2>
    <div class="table-wrap">{_table(experiment_df)}</div>
    <h2>Stream Summary</h2>
    <div class="table-wrap">{_table(stream_summary)}</div>
  </main>
</body>
</html>
"""
    out_path.write_text(html_body, encoding="utf-8")
    return out_path


def _metric_cards(
    *,
    intervals: pd.DataFrame,
    runs: pd.DataFrame,
    total_df: pd.DataFrame,
    flow_fairness: pd.DataFrame,
    stream_fairness: pd.DataFrame,
) -> str:
    run_count = runs["run_id"].nunique() if "run_id" in runs.columns and not runs.empty else 0
    flow_count = intervals["flow_id"].nunique() if "flow_id" in intervals.columns and not intervals.empty else 0
    stream_count = intervals["stream_id"].nunique() if "stream_id" in intervals.columns and not intervals.empty else 0
    avg_total = total_df["throughput_mbps"].mean() if "throughput_mbps" in total_df.columns and not total_df.empty else None
    flow_jain = flow_fairness["jain_fairness"].mean() if "jain_fairness" in flow_fairness.columns and not flow_fairness.empty else None
    stream_jain = stream_fairness["jain_fairness"].mean() if "jain_fairness" in stream_fairness.columns and not stream_fairness.empty else None
    duration = intervals["end_s"].max() - intervals["start_s"].min() if not intervals.empty else None

    return "\n".join(
        [
            _card("Runs", run_count),
            _card("Flows", flow_count),
            _card("Streams", stream_count),
            _card("Duration", _format(duration, "s")),
            _card("Mean Total Throughput", _format(avg_total, "Mbps")),
            _card("Mean Flow Fairness", _format(flow_jain, "")),
            _card("Mean Stream Fairness", _format(stream_jain, "")),
        ]
    )


def _card(label: str, value: object) -> str:
    return f"<div class=\"card\"><span>{html.escape(label)}</span><strong>{html.escape(str(value))}</strong></div>"


def _plot_section(artifact: PlotArtifact, report_dir: Path) -> str:
    rel_path = artifact.path.relative_to(report_dir) if artifact.path.is_relative_to(report_dir) else artifact.path
    return f"""<figure>
  <img src="{html.escape(str(rel_path))}" alt="{html.escape(artifact.title)}">
  <figcaption><strong>{html.escape(artifact.title)}</strong><br>{html.escape(artifact.description)}</figcaption>
</figure>"""


def _table(df: pd.DataFrame) -> str:
    if df.empty:
        return "<p class=\"muted\">No rows available.</p>"
    display = df.copy()
    for col in display.select_dtypes(include=["float"]).columns:
        display[col] = display[col].map(lambda value: "" if pd.isna(value) else f"{value:.3f}")
    return display.to_html(index=False, escape=True, border=0)


def _format(value: object, suffix: str) -> str:
    if value is None or pd.isna(value):
        return "n/a"
    if isinstance(value, (int, float)):
        return f"{value:.3f} {suffix}".strip()
    return str(value)
